name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL}}"
          push: true
          tags: hoaithu86/test-management:latest

      - name: Log in to the EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            docker stop test-management || true
            docker rm test-management || true
            docker rmi hoaithu86/test-management:latest
            docker pull hoaithu86/test-management:latest
            docker run -d --restart=always --name=test-management -p 80:3000 hoaithu86/test-management:latest
